---
  - name: Check pyCharm Installed
    stat: path=/opt/pyCharm
    register: check_pyCharm_installed

  - name: Download pyCharm
    get_url: url=https://download.jetbrains.com/python/pycharm-professional-2016.2.2.tar.gz dest=/home/{{user}}/Downloads/pycharm-professional-2016.2.2.tar.gz
    when: check_pyCharm_installed.stat.exists == False
    notify:
     - Rename pyCharm Dir

  - name: Install pyCharm
    unarchive: src=/home/{{user}}/Downloads/pycharm-professional-2016.2.2.tar.gz dest=/opt remote_src=yes
    when: check_pyCharm_installed.stat.exists == False
    notify:
     - Rename pyCharm Dir
