---
  - name: Check pyCharm Installed
    stat: path=/opt/pyCharm
    register: check_pyCharm_installed

  - name: Install pyCharm
    unarchive: src=https://download.jetbrains.com/python/pycharm-professional-2016.2.2.tar.gz dest=/opt remote_src=yes
    when: check_pyCharm_installed.stat.exists == False
    notify:
     - Rename pyCharm Dir
