# To use /etc/ansible/hosts
# ansible-playbook -K -u {{user}} -k /path/to/dev-setup.yml
#
# To use inventory file
# ansible-playbook -i /path/to/inventory /path/to/dev-setup.yml
---
- hosts: development_vm
  tasks:
    - name: Install packages
      apt: name={{item}} state=installed update_cache=true
      with_items:
        - htop
        - vim
        - python-pip
      become: true
  roles:
    - source-control
    - user-files
    - pyCharm
    - beyond-compare
    - dropbox
    - liquid-prompt
    - sensible-tmux
    - virtualenv-wrapper

# TODO:
# vscode
# chrome / postman
# Variety desktop switcher