---
  - name: Copy private SSH Key
    copy: src=id_rsa dest=/home/{{user}}/.ssh/id_rsa owner={{user}} group={{user}} mode=0600

  - name: Copy public SSH Key
    copy: src=id_rsa.pub dest=/home/{{user}}/.ssh/id_rsa.pub owner={{user}} group={{user}} mode=0644

  - name: Copy .gitconfig
    template: src=.gitconfig dest=/home/{{user}}/.gitconfig owner={{user}} group={{user}} mode=644

  - name: Copy .gitignore_global
    copy: src=.gitignore_global dest=/home/{{user}}/.gitignore_global owner={{user}} group={{user}} mode=0644

  - name: set vim as default editor
    command: update-alternatives --set editor {{editor}}
