---
  - name: Download Dropbox
    get_url: url=https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb dest=/home/{{user}}/Downloads/dropbox_2015.10.28_amd64.deb
    when: dropbox_check_deb.rc == 1
    notify:
     - Install Dropbox

  - name: Install Dropbox
    apt: deb=/home/{{user}}/Downloads/dropbox_2015.10.28_amd64.deb
    when: dropbox_check_deb.rc == 1